### ISSUE TITLE
friend init issues

### ISSUE THREAD

**Issue by jasonazzarella** [Hackathon-Squad/friendbot#1]
Hi @trulyronak @shravanhariharan2 @agop2020 !

I'm having trouble with /friend init not initializing. I have added friendbot into discord and all of the other commands seem to respond but init doesn't seem to do anything. I know this is about a year old project but this is exactly what we are looking for to help with socializing/networking. Would you folks be able to provide some guidance? We have this bound with thefriendbot.github.io.

You folks rock! Thanks.

**Comment by trulyronak** [comment]
Thanks for checking us out! Unfortunately we're not actively maintaining the project right now, but your best bet would be to run it locally - we don't host the bot anymore, so it's likely that the db connection has failed.

If you run it locally / link to your own firebase connection, you should be able to deploy and run it without issues

**Comment by jasonazzarella** [comment]
Welp! That makes more sense. Haha. Thanks for dev'in this sucker up. I'll get it rollin locally and see what I can do. <3
